/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as ProjectsProject_defaultRouteImport } from './routes/projects/project_default'
import { Route as GridviewGridRouteImport } from './routes/gridview/grid'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProject_defaultRoute = ProjectsProject_defaultRouteImport.update({
  id: '/projects/project_default',
  path: '/projects/project_default',
  getParentRoute: () => rootRouteImport,
} as any)
const GridviewGridRoute = GridviewGridRouteImport.update({
  id: '/gridview/grid',
  path: '/gridview/grid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gridview/grid': typeof GridviewGridRoute
  '/projects/project_default': typeof ProjectsProject_defaultRoute
  '/posts': typeof PostsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gridview/grid': typeof GridviewGridRoute
  '/projects/project_default': typeof ProjectsProject_defaultRoute
  '/posts': typeof PostsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gridview/grid': typeof GridviewGridRoute
  '/projects/project_default': typeof ProjectsProject_defaultRoute
  '/posts/': typeof PostsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gridview/grid'
    | '/projects/project_default'
    | '/posts'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gridview/grid'
    | '/projects/project_default'
    | '/posts'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gridview/grid'
    | '/projects/project_default'
    | '/posts/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GridviewGridRoute: typeof GridviewGridRoute
  ProjectsProject_defaultRoute: typeof ProjectsProject_defaultRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/project_default': {
      id: '/projects/project_default'
      path: '/projects/project_default'
      fullPath: '/projects/project_default'
      preLoaderRoute: typeof ProjectsProject_defaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gridview/grid': {
      id: '/gridview/grid'
      path: '/gridview/grid'
      fullPath: '/gridview/grid'
      preLoaderRoute: typeof GridviewGridRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GridviewGridRoute: GridviewGridRoute,
  ProjectsProject_defaultRoute: ProjectsProject_defaultRoute,
  PostsIndexRoute: PostsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
